OM-175 - Vector search dashboard
aerospike/aerospike-monitoring pull request #108
Opened 2024-03-27 17:59 UTC by mphanias

initial checkin of vector search dashboard

2024-03-28 22:41 UTC, hev requested changes
This is looking good a few thoughts. I reviewed this by hooking it up to our demo which has 1M images. Click [this link](http://34.122.59.14:3000/d/fzUPYeJIk/aerospike-proximus-cluster-view?orgId=1&refresh=1m&var-DS_AEROSPIKE_PROMETHEUS=P07E1502634787998&var-job_name=proximus&var-cluster=ptrial-image-demo&var-instance=All&var-index=All&from=now-30d&to=now) on VPN to see it. 

1. I'd like to get a sense of how many vectors are in proximus in addition to the index size.
2. A metric for overall write rate into proximus is needed. We we're trying to see how much load we were putting on proximus when we were embedding the images and it was hard to figure out. Ideally we can just get a metric for puts into proximus
3. No matter what I do I can't seem to get the query rate to budge. 

Just a few initial thoughts.

2024-03-28 22:41 UTC, hev commented on config/grafana/dashboards/vectorsearch/vector_search_view.json
> +  "description": "Proximus View dashboard helps visualise indexed, query success/error in selected proximus cluster",
Let's use the name Aerospike Vector Search (AVS) instead of proximus.

2024-04-04 18:17 UTC, thecloudslayer approved these changes

2024-04-23 17:01 UTC, hev requested changes
A few more changes.

* I'd like to see storage (in GB) in the main panel
* reocmmending the lablel "Indexed Vectors" instead of Index Count. This is clearer
* The different query types are not clear to me

2024-05-08 02:43 UTC, arrowplum commented on config/grafana/dashboards/vectorsearch/vector_search_view.json
> +  "title": "Aerospike Vector Service",
I think it is now no longer a service but a search

```suggestion
  "title": "Aerospike Vector Search",
```

2024-05-09 13:37 UTC, hev commented on config/grafana/dashboards/vectorsearch/vector_search_view.json
> +  "title": "Aerospike Vector Service",
Yep.

2024-06-19 06:37 UTC, merged