[TOOLS-2087 ] Add server6.1 metrics.
aerospike/aerospike-monitoring pull request #36
Opened 2022-08-09 18:30 UTC by dwelch-spike

2022-08-17 11:57 UTC, spkesan requested changes
Otherwise LGTM.

2022-08-17 11:57 UTC, spkesan commented on config/grafana/dashboards/xdr.json
> +          "expr": "sum(aerospike_xdr_bytes_shipped{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
We might want to apply a rate() over it as it is a cumulative value.

2022-08-18 00:54 UTC, dwelch-spike commented on config/grafana/dashboards/xdr.json
> +          "expr": "sum(aerospike_xdr_bytes_shipped{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
made the change

2022-08-18 01:53 UTC, spkesan approved these changes

2022-08-18 17:00 UTC, merged