adds set dashboard
aerospike/aerospike-monitoring pull request #40
Opened 2023-03-16 22:35 UTC by hev

This adds a new set dashboard for the set quotas features (and a few other metrics not on a dashboard currently).

2023-03-20 11:25 UTC, spkesan requested changes
Can you also add a screenshot of how this dashboard looks like with example data values.

2023-03-20 11:25 UTC, spkesan commented on config/grafana/dashboards/set.json
> +          "expr": "aerospike_sets_stop_writes_count{set=\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\", ns=\"$namespace\"}",
`aerospike_sets_stop_writes_size`

2023-03-20 11:25 UTC, spkesan commented on config/grafana/dashboards/set.json
> +      "description": "More details about [stop writes count](https://docs.aerospike.com/reference/configuration#stop-writes-size).",
`[stop writes size]`

2023-03-20 11:25 UTC, spkesan commented on config/grafana/dashboards/set.json
> +          "expr": "((aerospike_sets_device_data_bytes{set=~\"$set\", cluster_name=\"$cluster\", ns=\"$namespace\", job=\"$job_name\"} + aerospike_sets_memory_data_bytes{set=~\"$set\", cluster_name=\"
Where does this expression come from?

2023-03-20 21:58 UTC, hev commented on config/grafana/dashboards/set.json
> +          "expr": "aerospike_sets_stop_writes_count{set=\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\", ns=\"$namespace\"}",
fixed in [be18af4](https://github.com/aerospike/aerospike-monitoring/pull/40/commits/be18af44383805160f2bfdd6cef5d4a288cbe469)

2023-03-20 21:58 UTC, hev commented on config/grafana/dashboards/set.json
> +      "description": "More details about [stop writes count](https://docs.aerospike.com/reference/configuration#stop-writes-size).",
fixed in [a465790](https://github.com/aerospike/aerospike-monitoring/pull/40/commits/a465790bbac3fcc4cb6f83cf211c0369f8330c7c)

2023-03-20 22:00 UTC, hev commented on config/grafana/dashboards/set.json
> +          "expr": "((aerospike_sets_device_data_bytes{set=~\"$set\", cluster_name=\"$cluster\", ns=\"$namespace\", job=\"$job_name\"} + aerospike_sets_memory_data_bytes{set=~\"$set\", cluster_name=\"
@mphanias  used it in his Namespace dashboard. It prevents the bar guage from showing maxxed out when the value is not set. (see the testset2 in the screenshot).

2023-03-20 22:00 UTC, hev commented on config/grafana/dashboards/set.json
> +          "expr": "aerospike_sets_stop_writes_count{set=\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\", ns=\"$namespace\"}",
Screenshot added above.

2023-03-20 22:56 UTC, dwelch-spike commented
@hev Are all these panels cumulative for all sets or are they per set? I see all sets selected but notice the panels have the "testset" heading.

2023-03-20 23:11 UTC, dwelch-spike commented
> @hev Are all these panels cumulative for all sets or are they per set? I see all sets selected but notice the panels have the "testset" heading.

didn't see the 2nd set. Looks like they are individual.

2023-03-20 23:17 UTC, dwelch-spike commented
are the colors on the top left memory panel off? Limit is brown/red in the legend but looks like the line is green in the graph.

2023-03-20 23:30 UTC, dwelch-spike requested changes
Just a couple things that look like legend copy paste mistakes. One question about duplicated refID. After those have been looked at LGTM.

2023-03-20 23:30 UTC, dwelch-spike commented on config/grafana/dashboards/set.json
> +          "legendFormat": "Truncations",
Wrong legendFormat?

2023-03-20 23:30 UTC, dwelch-spike commented on config/grafana/dashboards/set.json
> +          "legendFormat": "Stop Writes Count",
Wrong legendFormat?

2023-03-20 23:30 UTC, dwelch-spike commented on config/grafana/dashboards/set.json
> +          "refId": "StandardVariableQuery"
Not sure how much this matters but seems like "StandardVariableQuery" is duplicated alot.

2023-03-21 02:06 UTC, hev commented on config/grafana/dashboards/set.json
> +          "legendFormat": "Truncations",
I exported the JSON from GrafanaUI and am not really sure where this comes from.

2023-03-21 02:06 UTC, hev commented on config/grafana/dashboards/set.json
> +          "refId": "StandardVariableQuery"
Another weird grafana thing?

2023-03-21 02:07 UTC, hev commented
@dwelch-spike - yeah, the panels repeat per set. Regarding the colors I wasn't able to figure out a way to set unique colors per query tho there probably is one.

2023-03-29 21:19 UTC, hev commented
One more comment here. I remove the option to show all namespaces. All sets across all namepsaces is likely to be too much data for grafana to render in certain circumstances.

2023-03-29 21:34 UTC, spkesan requested changes
Can we simplify the stop writes count panel (and any other similar panel). Like, `10000` should be displayed as `10K`. Otherwise LGTM. Thanks

2023-03-29 21:34 UTC, spkesan commented on config/grafana/dashboards/set.json
> +                  "text": "Not Set"
Can we change this to something small as `N/A`?

2023-03-29 21:42 UTC, hev commented on config/grafana/dashboards/set.json
> +                  "text": "Not Set"
I prefer Not Set in this case as this is configuration that the user has not yet set as opposed t he data being not available.

2023-03-29 21:43 UTC, hev commented on config/grafana/dashboards/set.json
> +                  "text": "Not Set"
The object count should already be using a "short" unit and display as rounded. See below. 
<img width="836" alt="Set_Dashboard_-_Dashboards_-_Grafana" src="https://user-images.githubusercontent.com/20188639/228674416-1fdc75f5-c9f4-4749-a2c9-02837851416f.png">

2023-03-30 00:53 UTC, dwelch-spike approved these changes
LGTM

2023-03-30 01:10 UTC, spkesan commented on config/grafana/dashboards/set.json
> +                  "text": "Not Set"
<img width="141" alt="Screenshot 2023-03-30 at 06 40 14" src="https://user-images.githubusercontent.com/11476298/228702063-a9c35aa3-7955-4d66-8ffc-467e6b433468.png">
In this panel.

2023-03-30 20:51 UTC, hev commented on config/grafana/dashboards/set.json
> +                  "text": "Not Set"
Got it. Thanks @spkesan

2023-03-31 07:01 UTC, merged