Monitoring Dashboard - March 2023 Release
aerospike/aerospike-monitoring pull request #41
Opened 2023-03-27 08:07 UTC by mphanias

this pull request includes below changes
1. NSUP metrics in Namespace view
2. Set Quota metrics in Namespace view 
3. Unique Data usage
4. Prometheus Alert rules for NSUP, Set Quota and stop-writes-sys-memory-pct

2023-03-27 23:19 UTC, hev requested changes

2023-03-27 23:19 UTC, hev commented on config/grafana/dashboards/uniquedata.json
> +      "title": "Cluster wise - Unique Data Usage ",
Let's remove the "wise" here.

2023-03-27 23:19 UTC, hev commented on config/grafana/dashboards/uniquedata.json
> +          "unit": "none"
We should use a bytes unit if this is in bytes.

2023-03-27 23:19 UTC, hev commented on config/grafana/dashboards/uniquedata.json
> +      "title": "Namespace wise - $namespace",
Drop the wise.

2023-03-27 23:19 UTC, hev commented on config/grafana/dashboards/uniquedata.json
> +      "description": "Display Unique Data Utilization by namespaces in bytes",
This panel has a very complicated formula. It would be helpful to provide better context about what it's doing and why you would care about unique data.

2023-03-27 23:19 UTC, hev commented on config/grafana/dashboards/node.json
What are the changes implemeting in the node dashboard? Just migrating to updatd version?

2023-03-27 23:19 UTC, hev commented on config/prometheus/aerospike_rules.yml
> +    - alert: NamespaceSetQuotaAlert
We should add a similar alerts for set level stop write quotas.

2023-03-27 23:20 UTC, hev commented on config/prometheus/aerospike_rules.yml
> +    - alert: NamespaceSetQuotaAlert
This one technically covers namespace (instead of sets).

2023-03-28 16:54 UTC, hev commented on config/grafana/dashboards/uniquedata.json
> +          "unit": "none"
Leaving this for now as we have inconsitency across bytes broadly.

2023-03-28 20:08 UTC, hev commented on config/grafana/dashboards/uniquedata.json
> +      "description": "Display Unique Data Utilization by namespaces in bytes",
Some more explanation here would be nice but I don't want to hold the PR on this. Marking resolved.

2023-03-28 20:09 UTC, hev approved these changes
Changes look good. Thanks @mphanias

2023-03-31 07:10 UTC, sunilvirus approved these changes
Looks good to me.

2023-03-31 07:14 UTC, merged