Om 100 - bug fixes in master-cluster-view, alerts-view and unique-data-view
aerospike/aerospike-monitoring pull request #63
Opened 2023-07-31 15:37 UTC by mphanias

unique-data view - fixed bugs 1) unique-data-bytes are not displayed when geo-location is added and 2) query to honour selected namespaces
and 3) added a historical time series panel
alerts view - fixed display colour and show alerts specific to selection criteria
multi-cluster-view: fixed Grafana version to 9.x, XDR and Latencies point to respective dashboards (instead of cluster-view dashboard). added enhancement to filter using alert-severity

2023-08-01 05:50 UTC, mphanias commented
action file python-lint.yml: moved python library to check-jsonschema as (existing jsonschema is having issues while installing and may get deprecate in future)

2023-08-02 22:02 UTC, hev approved these changes
Tested the dashboards. Links look good. Didn't notice much changed in AlertsView and unique data but worked fine.

2023-08-03 03:10 UTC, hev requested changes
See detail about default data source.

2023-08-03 03:10 UTC, hev commented on config/grafana/provisioning/datasources/all.yaml
> -    isDefault: false
This is setting alert manager as default instead of Aerospike Prometheus

2023-08-03 10:07 UTC, sunilvirus approved these changes
Offline review comments addressed

2023-08-03 10:09 UTC, sunilvirus commented on config/grafana/provisioning/datasources/all.yaml
> -    isDefault: false
Addressed.

2023-08-03 10:11 UTC, merged